language: go

before_script:
  - go get -u -v github.com/spf13/hugo

install:
  - rm -rf public || exit 0

script:
  - hugo version
  - hugo config
  - hugo env
  - hugo list drafts
  - hugo list expired
  - hugo list future
  - hugo -v -F

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  fqdn: ricardorocha.io
  github_token: $GITHUB_TOKEN
  on:
    branch: master
