baseurl = "https://ricardorocha.io/"
languageCode = "en-us"
title = "Ricardo Rocha"
theme = "hugo-cactus-theme"

[permalinks]
  post = "/:year/:month/:day/:title/"
  page = "/:title/"

[params]
  name = "Ricardo Rocha"
  description = "Software Engineer at CERN"
  bio = "Code - Mountains - Flying"
  twitter = "ahcorporto"
  enableRSS = true
  customCSS = []
  customJS  = []
  home = ""
  about = ""
  subscribe = ""
  olderPosts = ""
  newerPosts = ""
  readMore = "Latest Content"
  copyright = "@ Copyright 2018 Ricardo Rocha, Built with <a href='http://gohugo.io'>Hugo</a>"
  aboutAuthor = ""
  tweet = ""
  share = "nothing"
  title404 = ""
  subtitle404 = ""
  socialIconStyle = "rounded"

# Add additional social link entries underneath
[social]
  twitter  = "https://twitter.com/ahcorporto"
  github   = "https://github.com/rochaporto"
  linkedin = "https://www.linkedin.com/in/ricardo-rocha-739aa718"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[[menu.main]]
  name = "Blog"
  weight = -200
  url = "/blog/"
[[menu.main]]
  name = "Projects"
  weight = -190
  url = "/project"
[[menu.main]]
  name = "Talks"
  weight = -180
  url = "/talk/"
[[menu.main]]
  name = "Stories"
  weight = -170
  url = "/story/"
